"use strict";
// JARVIS skill playbooks — an in-memory catalog served by app/src/skills.js. The LLM
// reads these on demand via the list_skills / get_skill tools to get detailed,
// step-by-step guidance for a capability before an unfamiliar or multi-step task.
// Edit this file and restart the app (./JARVIS.sh --reload) to update the skills.
module.exports = [
  {
    name: "memory",
    category: "memory",
    summary: "Semantic memory (Mem0) for facts; a workbench database for structured data.",
    details: [
      "PRIMARY (facts about the user/world): use the semantic memory tools, backed by Mem0 + a vector store.",
      "  - add_memory(text): save a durable fact in natural language; it auto-extracts, dedupes, and updates conflicting facts.",
      "  - search_memory(query): recall BY MEANING (not exact match). ALWAYS search before answering anything personal — name, family, home, preferences, prior decisions.",
      "  - update_memory(id, text): correct a fact IN PLACE (moved house, changed preference) — prefer this over delete + re-add.",
      "  - list_memories() / delete_memory(id): review and prune. search results include created_at + any metadata you saved.",
      "  Semantic memory is the right tool when the user says 'remember that ...' or asks 'what do you know about me / what's my ...'.",
      "STRUCTURED/TABULAR data (lists, logs, time-series, joins, aggregates): create a local database in your workbench via run_shell — DuckDB or SQLite under /LLM_WORKSPACE, which persists across rebuilds.",
      "  - e.g. `duckdb /LLM_WORKSPACE/data.db \"CREATE TABLE tickers(sym TEXT, price DOUBLE); INSERT ...; SELECT ...\"` or use the python duckdb/sqlite3/pandas libraries.",
      "Rule of thumb: a fact in a sentence -> add_memory; rows in a table -> a DuckDB/SQLite file in /LLM_WORKSPACE.",
    ].join("\n"),
  },
  {
    name: "workbench-shell",
    category: "system",
    summary: "Run commands / install software in your root Linux workbench.",
    details: [
      "run_shell executes bash as ROOT in your Ubuntu workbench. ~2000 tools are preinstalled (python3, node, go, java, git, gh, curl, wget, jq, ripgrep, ffmpeg, imagemagick, pandoc, mysql/psql/redis/sqlite clients, nmap, etc.).",
      "Your working directory is /LLM_WORKSPACE and it PERSISTS across image rebuilds (a named volume). Use it as your scratch/build area (in-progress work, dependencies, temp files); /tmp and most other paths are ephemeral.",
      "Create code/config files with write_workbench_file(path, content) — it writes reliably with ANY content (quotes, backticks, newlines), unlike run_shell heredocs/echo which are error-prone. Then run them with run_shell. (Use write_file -> /LLM_READ_WRITE_FILES only for files you hand to the user.)",
      "DELIVERABLES: anything you make FOR the user (final files, programs, reports, generated data) must be saved to /LLM_READ_WRITE_FILES (mounted in the workbench too) so it appears on the user's computer — copy finished output there, e.g. `cp /LLM_WORKSPACE/out.csv /LLM_READ_WRITE_FILES/`. Do not leave the user's deliverables only in /LLM_WORKSPACE.",
      "Python: use `uv` for fast per-project envs/installs (`uv venv`, `uv pip install ...`, `uv run ...`); or `pip install --break-system-packages`. Preinstalled data/ML: pandas, polars, duckdb, numpy, scipy, scikit-learn, pyarrow, sqlalchemy, jupyterlab.",
      "Local testing: spin up SQLite/DuckDB directly; mysql/psql/redis clients are present for hitting databases.",
      "TEST YOUR CODE: after writing any script/program, RUN it on a representative input and confirm the output is correct and the exit code is 0 (catch and fix errors, re-run) BEFORE telling the user it's done — never hand over untested code. Add a quick smoke test for anything non-trivial.",
      "Install anything else with apt-get: `apt-get update && apt-get install -y <pkg>` (you are root).",
      "DISPLAY=:1 is preset, so GUI programs you launch appear on the desktop the user is watching.",
      "Long output is truncated; write large results to /LLM_READ_WRITE_FILES or summarize.",
    ].join("\n"),
  },
  {
    name: "internet",
    category: "internet",
    summary: "Read web pages/APIs (fetch_url) and search the web (web_search).",
    details: [
      "web_search(query) returns result titles, URLs, and snippets. If it reports being rate-limited/blocked, that is NOT 'no results' — wait and retry, or go straight to a known site. Pick relevant results, then fetch_url(url) to read them (HTML is stripped to text; long pages page via offset).",
      "fetch_url also calls HTTP APIs: pass method, headers (e.g. Authorization with a token from get_secret), and a json or body payload. For a binary download (PDF/image/zip) pass save_to:'downloads/<name>' to save it to the shared folder, then use read_document or analyze_image on it.",
      "For anything INTERACTIVE on a website (clicking, forms, login, JS-heavy pages), use the browser_* tools instead of fetch_url — see the 'browser' skill.",
      "You have OPEN internet access (no allow-list). Prefer official APIs when available.",
      "Research flow: 2-3 differently-phrased web_search queries -> fetch_url the best 1-3 (prefer primary/official sources, note dates) -> synthesize, stating what's sourced vs inferred -> (optionally) write findings to /LLM_READ_WRITE_FILES or a DuckDB file in /LLM_WORKSPACE.",
    ].join("\n"),
  },
  {
    name: "web-preview",
    category: "desktop",
    summary: "Let the user preview/test a web app in their own browser before you hand over the code.",
    details: [
      "GOAL: the user opens a URL and gets a WORKING, interactive page. The #1 mistake is building only API endpoints (POST /save, GET /data) with no UI — then GET / is 'Cannot GET /' and it looks broken. ALWAYS serve a real HTML page at GET / with the actual interface (forms, buttons, fetch() calls to your own endpoints).",
      "Steps: 1) build the app under /LLM_WORKSPACE; 2) serve_app(command, port) on a preview port 9101-9150 bound to 0.0.0.0; 3) check the result — ok_homepage must be true / status 200 at /. If not, FIX it (usually: add the homepage route/index.html) and call serve_app again. Only tell the user the URL once GET / returns 200.",
      "4) TEST the actual functionality before handing over: curl the API routes (e.g. POST to the form endpoint then GET it back and confirm the data round-trips), and/or use Playwright to load the page, submit input, and verify the response. Fix any failure and re-run. Then tell the user the URL and briefly what you tested.",
      "Bind to 0.0.0.0 (NOT 127.0.0.1/localhost) and use a preview port 9101-9150 (port 3000/8080 etc. are NOT exposed to the host).",
      "Prefer the SIMPLEST stack that shows a UI: a single static index.html (serve with `python3 -m http.server <port> --bind 0.0.0.0`), or one Express/Flask file that returns an HTML page at '/' and has any API routes it needs. Avoid heavy build steps (Vite/Next) for a quick demo unless asked.",
      "Iterate in place: keep ONE app dir, fix and re-run serve_app — do not scatter multiple half-built attempts.",
      "Minimal known-good Express demo (one file serves the UI at / AND an API):",
      "  const e=require('express'),app=e();app.use(e.json());let items=[];",
      "  app.get('/',(q,r)=>r.type('html').send(`<h1>Demo</h1><input id=i><button onclick=\"fetch('/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({v:i.value})}).then(()=>load())\">Add</button><ul id=l></ul><script>async function load(){l.innerHTML=(await (await fetch('/items')).json()).map(x=>'<li>'+x+'</li>').join('')}load()</script>`));",
      "  app.post('/add',(q,r)=>{items.push(q.body.v);r.json({ok:true})});app.get('/items',(q,r)=>r.json(items));",
      "  app.listen(9105,'0.0.0.0',()=>console.log('up'));",
      "Then: serve_app('node app.js', 9105). After the user is happy, save the final source to /LLM_READ_WRITE_FILES.",
    ].join("\n"),
  },
  {
    name: "browser",
    category: "internet",
    summary: "Work with websites deterministically via the browser_* tools (click, fill, extract by selector).",
    details: [
      "For ANYTHING inside a website — read, click, fill forms, log in, multi-step flows — use the browser_* tools. They drive a real, persistent Chromium (visible on the workbench desktop; logins/cookies persist), targeting elements by DOM ref or CSS selector — NOT pixel coordinates. This is far more reliable than screenshot+click.",
      "browser_goto(url): open a page.",
      "browser_snapshot(): see the page — URL, title, a text preview, and the visible interactive elements each with a short ref (e.g. 'e3') plus tag/text/name. Refs go STALE after navigation — snapshot again.",
      "browser_click(target): click by ref ('e3') or CSS selector ('button[type=submit]', 'text=Sign in').",
      "browser_fill(target, text, press_enter?): type into an input; set press_enter=true to submit.",
      "browser_extract(selector?): get the EXACT visible text of the page (or one element) — use this to READ content, not the vision screenshot. Pages via offset.",
      "Flow: browser_goto -> browser_snapshot -> act by ref/selector -> snapshot again to verify. Login: browser_fill the user/pass fields (creds from get_secret) -> browser_click submit -> snapshot to confirm. Stop and ask the user if a CAPTCHA / phone verification appears.",
      "Advanced: for heavy scraping/automation you can still script Playwright directly via run_shell (python3, Chromium+Firefox preinstalled), saving screenshots to /LLM_READ_WRITE_FILES.",
    ].join("\n"),
  },
  {
    name: "desktop-control",
    category: "desktop",
    summary: "See and operate NON-browser GUI apps on the watchable desktop.",
    details: [
      "This is pixel-level computer use for the on-screen GUI the user is watching. For websites use the 'browser' skill instead (deterministic, no guessing) — only use this for non-browser apps or when you must drive the visible desktop.",
      "screenshot(question?) captures the screen and returns a TEXT analysis from a vision model: what is visible + interactive elements with their approximate CENTER pixel coordinates (x,y from the top-left). Pass a focused question (e.g. 'where is the Save button?'). The screen is 1024x768.",
      "Act on those coordinates with: click(x,y), double_click, right_click, move_mouse, type_text(text), press_key(keys) [xdotool keysyms: Return, Tab, ctrl+l, ctrl+s, BackSpace; sequences like 'ctrl+a BackSpace' are OK], scroll(direction, amount). Move over a target before scrolling.",
      "ui_actions([...]) runs a SEQUENCE of those actions in ONE call (fewer round-trips), e.g. click a field -> type -> key Return. It stops at the first failing step and tells you which — check the result.",
      "Loop: screenshot -> act (or ui_actions) -> screenshot to verify -> repeat. Never act blind; use the coordinates from the latest screenshot.",
      "analyze_image(path, question) does the same visual analysis on an image FILE (e.g. a user upload in /LLM_READ_WRITE_FILES/uploads/) — see the 'vision' skill.",
    ].join("\n"),
  },
  {
    name: "shared-files",
    category: "files",
    summary: "Exchange files with the user via the shared folders.",
    details: [
      "list_dir, read_file, write_file operate in the shared folders.",
      "/LLM_READ_ONLY_FILES is READ-ONLY to you (the user puts files there for you to read).",
      "/LLM_READ_WRITE_FILES is READ/WRITE — put any files you produce there so the user can pick them up.",
      "write_file OVERWRITES by default; pass append=true to add to the end (it also guarantees each entry starts on a new line).",
      "For recurring/periodic LOGS, use append_log(path, message) instead — the code stamps a uniform ISO timestamp and writes exactly one consistent line per entry, so a logging task never drifts in format or runs lines together across runs. Pass optional structured data via fields={k:v}. Do NOT add your own timestamp.",
      "For big outputs from run_shell, write to /LLM_READ_WRITE_FILES rather than dumping into chat.",
    ].join("\n"),
  },
  {
    name: "app-integration",
    category: "files",
    summary: "Work WITH an installed app that has its OWN data directory (don't assume /LLM_WORKSPACE).",
    details: [
      "When the user asks you to operate ON an app that is already installed/running (add notes, records, content, config), the app reads/writes ITS OWN data location — NOT your /LLM_WORKSPACE scratch dir. Writing into /LLM_WORKSPACE means the app can't see it, and reading from /LLM_WORKSPACE gives you a stale copy. This is a common, wasteful mistake — avoid it.",
      "STEP 1 — find where the app actually stores data BEFORE touching anything: read the app's config/env/source. Look for a data dir / DB path / uploads/notes folder in its config.json, .env, docker-compose, or code (grep for paths like 'data', 'uploads', 'notes', 'DB_PATH', 'STORAGE', 'ROOT_DIR'). If it's a DB-backed app, find the DB file/connection and write through the app's API or directly into the DB — not into loose files.",
      "STEP 2 — confirm the real path: `ls` it and read an EXISTING record to learn the exact format/schema the app expects (e.g. a note may need real Markdown body content, front-matter, or a DB row — not a placeholder like the literal word 'Markdown').",
      "STEP 3 — write in that location/format, then VERIFY THROUGH THE APP: reload the app's page (browser_goto) or hit its API and confirm your change actually shows up. Do not report success from a file write alone.",
      "If the app's data lives in a shared location so BOTH of you can reach it (often under /LLM_READ_WRITE_FILES/<app>/...), use that path directly. If it lives only inside the app's own container/dir, go through the app's API/CLI.",
      "Three distinct locations — keep them straight: /LLM_WORKSPACE = YOUR scratch/build area; /LLM_READ_WRITE_FILES = the shared drop for files you hand the user; the installed APP's data dir = wherever that app is configured to read/write. Match the task to the right one.",
    ].join("\n"),
  },
  {
    name: "create-documents",
    category: "files",
    summary: "Create documents and images in any popular format in the workbench.",
    details: [
      "You are root with internet, so install whatever you need — never say you cannot.",
      "Preinstalled: pandoc, chromium, and Python libs fpdf2, reportlab, python-docx, python-pptx, openpyxl, pillow, matplotlib, markdown, plus imagemagick.",
      "PDF (programmatic): Python fpdf2 or reportlab (no external engine needed).",
      "PDF (formatted, from Markdown): pandoc `input.md -o tmp.html`, then `chromium --headless --no-sandbox --print-to-pdf=/LLM_READ_WRITE_FILES/out.pdf tmp.html`.",
      "Word DOCX: pandoc `-o out.docx`, or python-docx (programmatic control).",
      "PowerPoint PPTX: python-pptx. Excel XLSX: openpyxl. ODT/ODS/ODP, EPUB, RTF, HTML: pandoc.",
      "Images: Pillow (PIL) to create/edit, matplotlib for charts/plots, imagemagick `convert` for format conversion/resizing.",
      "CSV/JSON/TXT/MD: write directly with write_file.",
      "Always save the finished file into the read-write shared folder (/LLM_READ_WRITE_FILES) so the user gets it, then tell them the path.",
    ].join("\n"),
  },
  {
    name: "credentials",
    category: "credentials",
    summary: "Manage and use the user's OWN account logins (vault).",
    details: [
      "list_secrets -> names/usernames/urls (no passwords). get_secret(name) -> full credential incl. password, to log in.",
      "set_secret(name, {username,password,url,notes}) -> create or update (partial updates allowed). delete_secret(name) -> remove.",
      "Only operate accounts the user already OWNS. Do NOT create new accounts or bypass sign-up CAPTCHAs / phone verification.",
      "After the user gives you a login, save it with set_secret so you can reuse it.",
    ].join("\n"),
  },
  {
    name: "scheduling",
    category: "scheduling",
    summary: "Run tasks later/recurring and notify the user.",
    details: [
      "schedule_task(prompt, ...): one-shot with in_seconds (delay) or at (absolute ISO datetime); recurring with every_seconds plus an optional plain-language `until` stop condition.",
      "Compute times from the current date/time you are given each turn (e.g. 'in 10 minutes' -> in_seconds 600; 'at 5pm' -> today's ISO at 17:00).",
      "list_tasks to view; update_task(id, ...) to CHANGE an existing task in place (keeps it running — ALWAYS use this to modify a task, never cancel + reschedule); cancel_task(id) to stop one.",
      "OUTPUT DESTINATIONS — the task chooses where its result goes: post_to_chat(msg) speaks into the user's live chat window (use when the task should talk to the user); notify_user(msg) is a passive alert/badge AND the STOP signal for a recurring task (so only call it as the stop condition or for one-shots); append_log/write_file to /LLM_READ_WRITE_FILES is a persistent file. You can combine them.",
      "For a recurring monitor, call notify_user ONLY when the `until` condition is met (that stops the task); otherwise end with a one-line status.",
      "See the 'task-authoring' skill for how to WRITE the task prompt (each run is fresh + stateless).",
    ].join("\n"),
  },
  {
    name: "workflow-login-and-act",
    category: "workflow",
    summary: "Log into a site the user owns and do something there.",
    details: [
      "PREFERRED (a website) — use the browser_* tools (deterministic, no pixel guessing):",
      "  1) get_secret(name) for the account.",
      "  2) browser_goto(login URL).",
      "  3) browser_snapshot() to find the username/password fields (by ref or selector).",
      "  4) browser_fill the username field; browser_fill the password field with press_enter:true (or browser_click the sign-in button).",
      "  5) browser_snapshot() to confirm you're logged in, then continue the task.",
      "If the account is new, ask the user for the login and save it with set_secret so you can reuse it.",
      "If a CAPTCHA or phone verification appears, STOP and ask the user to complete it — never attempt to bypass it.",
      "Only for a non-browser app, fall back to the desktop-control pixel tools.",
    ].join("\n"),
  },
  {
    name: "workflow-monitor-and-alert",
    category: "workflow",
    summary: "Watch something on an interval and notify when a condition is met.",
    details: [
      "Use schedule_task with every_seconds (the interval) and until (the condition in plain language).",
      "Make the task prompt do the check (run_shell / fetch_url / browser_extract / check_email / screenshot as appropriate) — see 'task-authoring' for writing it well.",
      "When the condition is met, call notify_user with the important details — this stops the recurring task.",
      "When it is not met, just report a one-line status and do not notify.",
      "To escalate an unanswered prompt ('warn me, then urgent, if I don't reply'), use read_recent_chat(roles:['user']) to check whether the user has responded since your last message.",
      "The user can also say 'stop' and you cancel_task it.",
    ].join("\n"),
  },
  {
    name: "vision",
    category: "desktop",
    summary: "See images and the screen with the vision model.",
    details: [
      "Two ways to 'see':",
      "screenshot(question?) — the LIVE desktop the user is watching. Returns a text description + interactive-element coordinates. Ask a FOCUSED question ('what error is shown?', 'where is the address bar?') rather than 'describe this'.",
      "analyze_image(path, question?) — an image FILE. User uploads land in /LLM_READ_WRITE_FILES/uploads/; you can also fetch_url(save_to:...) an image then analyze it, or save a Playwright/browser screenshot and analyze it.",
      "For actions, chain vision -> coordinates -> ui_actions/click. To READ a web page's text, prefer browser_extract (exact) over a screenshot.",
      "Supported image types: png, jpg, gif, webp, bmp, tiff, svg (max ~8MB — downscale a larger one first with imagemagick `convert`).",
    ].join("\n"),
  },
  {
    name: "email",
    category: "communication",
    summary: "Read and send email from the user's OWN account.",
    details: [
      "Requires a vault secret named 'email' with {username, password, imap_host, smtp_host} (use an APP PASSWORD for Gmail/Outlook, not the login password). If it's missing, tell the user to add it via set_secret and which fields you need.",
      "check_email({folder?, limit?, unseen_only?}) -> recent messages (from/subject/date/uid).",
      "read_email({uid, folder?}) -> one message's body + attachment names (uid comes from check_email).",
      "send_email({to, subject, body}) -> send plain text FROM the user's account. CONFIRM with the user before sending anything they didn't explicitly ask you to send.",
      "Great in a scheduled task: 'every 15 min, check_email unseen_only and notify_user if something from my boss arrives'.",
    ].join("\n"),
  },
  {
    name: "documents",
    category: "files",
    summary: "Read text out of PDFs and Office documents.",
    details: [
      "read_document(path, offset?, max_chars?) extracts TEXT from PDF, DOCX, ODT, RTF, EPUB, or HTML in the shared folders (e.g. a user upload in /LLM_READ_WRITE_FILES/uploads/, or a file you downloaded with fetch_url save_to). Long docs page via offset.",
      "It's the right tool when read_file errors 'binary file' on a document. For images use analyze_image; for plain text/csv/json/logs use read_file.",
      "To CREATE documents (PDF/DOCX/PPTX/XLSX/images), see the 'create-documents' skill.",
    ].join("\n"),
  },
  {
    name: "data-analysis",
    category: "data",
    summary: "Analyze data/datasets in the workbench (pandas/polars/duckdb) and deliver results.",
    details: [
      "The workbench has pandas, polars, duckdb, numpy, scipy, scikit-learn, and matplotlib preinstalled — use run_shell / write_workbench_file.",
      "1) LAND the data in /LLM_WORKSPACE (a user upload from /LLM_READ_WRITE_FILES, a fetch_url download, or a DB query). For CSV/Parquet/JSON, duckdb reads files directly: `duckdb -c \"SELECT * FROM read_csv_auto('/LLM_WORKSPACE/data.csv') LIMIT 5\"`.",
      "2) SANITY-CHECK before analyzing: row count, column names/dtypes, null counts, obvious ranges. State what you found. Don't analyze data you haven't looked at.",
      "3) ANALYZE with SQL (duckdb) or pandas/polars. Keep the raw data immutable; derive new tables/frames.",
      "4) VERIFY numbers by re-querying a different way (e.g. cross-check a total) — never eyeball a figure and report it.",
      "5) VISUALIZE with matplotlib and save the PNG to /LLM_READ_WRITE_FILES; also save any result CSV there.",
      "6) DELIVER: a short findings summary + the chart + the data file in /LLM_READ_WRITE_FILES. Report exact numbers, and be explicit about caveats (sample size, missing data, assumptions).",
      "For big/repeated analysis, persist a DuckDB file in /LLM_WORKSPACE/data.db so you can re-query without reloading.",
      "Always TEST any analysis script (run it, check exit 0 and sane output) before reporting results.",
    ].join("\n"),
  },
  {
    name: "error-recovery",
    category: "system",
    summary: "What to do when a tool errors or returns nothing.",
    details: [
      "READ the actual error/output first — don't guess. Tools return structured results; a failure usually says why.",
      "TRANSIENT (network blip, rate limit, timeout, temporary 5xx): retry ONCE, maybe with a longer timeout_s or after a short wait. web_search saying 'blocked/rate-limited' is transient, not 'no results'.",
      "STRUCTURAL (wrong path, bad selector, missing dependency, 4xx, unsupported input): do NOT retry the same thing — change the approach (fix the path, install the package with apt/pip, use a different tool). E.g. read_file 'binary file' -> use read_document or analyze_image; browser selector not found -> browser_snapshot again for the real ref.",
      "run_shell that was KILLED by the timeout: raise timeout_s, or run it in the background (nohup ... &) and poll.",
      "EMPTY/NO DATA is a real outcome — report it honestly ('the log had no matching entries', 'the API returned []'). NEVER invent a value or claim success when a tool returned nothing.",
      "If genuinely stuck after a couple of distinct attempts, say what you tried, what failed, and what you'd need — don't loop the same failing call (the tool loop caps iterations anyway).",
    ].join("\n"),
  },
  {
    name: "task-authoring",
    category: "scheduling",
    summary: "How to WRITE a good scheduled-task prompt (each run is fresh + stateless).",
    details: [
      "A scheduled task's prompt is run by the model through its tools at run time — NOT executed as literal code. Each run is a brand-new, stateless conversation with no chat history, so the prompt must be fully SELF-CONTAINED.",
      "Name the EXACT tool(s), commands, and file paths. Use real API ids/URLs. Don't rely on anything from the current conversation.",
      "'every 5 minutes' etc. describes the schedule that already exists — do NOT put scheduling logic in the prompt body, and never schedule/cancel tasks from inside a task.",
      "For deterministic jobs (fetch + log), prefer ONE explicit run_shell, e.g. \"Run exactly this and report its output: curl -s <url> | jq .price >> /LLM_READ_WRITE_FILES/price.log\". Use append_log for consistent log formatting.",
      "Choose the output destination explicitly (post_to_chat to talk to the user; notify_user as the stop signal; append_log/write_file to persist) — see the 'scheduling' skill.",
      "For 'nudge me / escalate if I don't respond', have the run call read_recent_chat(roles:['user']) to see whether the user replied, and set the message importance accordingly.",
      "Be HONEST: report only what tools actually returned; if a check finds nothing or a tool errors, say so — never invent a result.",
    ].join("\n"),
  },
  {
    name: "survival-knowledge-base",
    category: "reference",
    prompts: ["survivalist"],   // specialty skill — only shown when the 'survivalist' prompt is active
    summary: "Answer survival/emergency questions FROM the offline Survival Knowledge Base (49 guides + manuals, maps, per-state info).",
    details: [
      "The knowledge base is an OFFLINE folder at /LLM_READ_ONLY_FILES/Survival_Knowledge_Base — 49 in-depth guides plus reference manuals, road/topo maps, and per-state local info. Answer survival, preparedness, and emergency questions FROM it, not from general memory.",
      "START HERE: read_file /LLM_READ_ONLY_FILES/Survival_Knowledge_Base/START-HERE.md — a life-threat triage plus a 'pick your situation' router to the right guide. Then INDEX.md for the full topic list, GLOSSARY.md for terms, CHECKLISTS.md for printable checklists.",
      "GUIDES: each topic is topics/<topic>/<topic>.md (e.g. topics/water/water.md, topics/first-aid/first-aid.md, topics/food-preservation-cooking/food-preservation-cooking.md). read_file the matching guide(s) and answer from their step-by-step sections; prefer the specific guide over general advice.",
      "DEEPER SOURCES: the reference manuals are PDFs in reference/manuals/ — use read_document on them. Images live in each topic's images/ folder, and the offline maps in reference/maps/ (national + all 50 state road maps + street-level North Texas) — use analyze_image to read/verify them.",
      "LOCATION: for a place-specific question also read reference/local/<state>.md (deepest for texas/oklahoma/arkansas; home base is Anna, TX). For radios/frequencies read reference/comms-frequencies.md.",
      "PRIORITIES: give calm, ordered steps following the guides' Rule of 3s (air/severe bleeding -> shelter/temperature -> water -> food) and the two key decisions (shelter-in-place vs evacuate; stay vs go). Offer more than one method when the guide gives them, with concrete quantities and times.",
      "SAFETY: for anything medical, chemical, electrical, or structural, repeat the guide's warnings, never invent drug/herbal doses, and say to get professional help the moment it's reachable. If it isn't in the KB or you're unsure, say so — never fabricate.",
      "CLICKABLE CITATIONS (open in a new tab): guide/section -> [Water — Method 1: Boiling](/view?dir=ro&path=Survival_Knowledge_Base/topics/water/water.md#method-1-boiling) where the anchor is the heading lowercased, punctuation dropped, spaces->hyphens. PDF -> [FM 21-76](/api/files/raw?dir=ro&path=Survival_Knowledge_Base/reference/manuals/fm21-76_survival_manual.pdf) (add #page=N if known). Image/map -> link the raw file the same way. End answers with a short 'Sources:' line linking the 1-3 guides you actually used.",
    ].join("\n"),
  },
];
