"use strict";
// JARVIS skill playbooks. Seeded into the `skills` table in the memory database
// on app startup (idempotent). The LLM reads these on demand via the
// list_skills / get_skill tools to get detailed, step-by-step guidance.
// Edit this file and restart the app to update the skills.
module.exports = [
  {
    name: "memory",
    category: "memory",
    summary: "Semantic memory (Mem0) for facts; a workbench database for structured data.",
    details: [
      "PRIMARY (facts about the user/world): use the semantic memory tools, backed by Mem0 + a vector store.",
      "  - add_memory(text): save a durable fact in natural language; it auto-extracts, dedupes, and updates conflicting facts.",
      "  - search_memory(query): recall BY MEANING (not exact match). ALWAYS search before answering anything personal — name, family, home, preferences, prior decisions.",
      "  - list_memories() / delete_memory(id): review and prune.",
      "  Semantic memory is the right tool when the user says 'remember that ...' or asks 'what do you know about me / what's my ...'.",
      "STRUCTURED/TABULAR data (lists, logs, time-series, joins, aggregates): create a local database in your workbench via run_shell — DuckDB or SQLite under /workspace, which persists across rebuilds.",
      "  - e.g. `duckdb /workspace/data.db \"CREATE TABLE tickers(sym TEXT, price DOUBLE); INSERT ...; SELECT ...\"` or use the python duckdb/sqlite3/pandas libraries.",
      "Rule of thumb: a fact in a sentence -> add_memory; rows in a table -> a DuckDB/SQLite file in /workspace.",
    ].join("\n"),
  },
  {
    name: "workbench-shell",
    category: "system",
    summary: "Run commands / install software in your root Linux workbench.",
    details: [
      "run_shell executes bash as ROOT in your Ubuntu workbench. ~2000 tools are preinstalled (python3, node, go, java, git, gh, curl, wget, jq, ripgrep, ffmpeg, imagemagick, pandoc, mysql/psql/redis/sqlite clients, nmap, etc.).",
      "Your working directory is /workspace and it PERSISTS across image rebuilds (a named volume). Use it as your scratch/build area (in-progress work, dependencies, temp files); /tmp and most other paths are ephemeral.",
      "Create code/config files with write_workbench_file(path, content) — it writes reliably with ANY content (quotes, backticks, newlines), unlike run_shell heredocs/echo which are error-prone. Then run them with run_shell. (Use write_file -> /READ_WRITE_FILES only for files you hand to the user.)",
      "DELIVERABLES: anything you make FOR the user (final files, programs, reports, generated data) must be saved to /READ_WRITE_FILES (mounted in the workbench too) so it appears on the user's computer — copy finished output there, e.g. `cp /workspace/out.csv /READ_WRITE_FILES/`. Do not leave the user's deliverables only in /workspace.",
      "Python: use `uv` for fast per-project envs/installs (`uv venv`, `uv pip install ...`, `uv run ...`); or `pip install --break-system-packages`. Preinstalled data/ML: pandas, polars, duckdb, numpy, scipy, scikit-learn, pyarrow, sqlalchemy, jupyterlab.",
      "Local testing: spin up SQLite/DuckDB directly; mysql/psql/redis clients are present for hitting databases.",
      "TEST YOUR CODE: after writing any script/program, RUN it on a representative input and confirm the output is correct and the exit code is 0 (catch and fix errors, re-run) BEFORE telling the user it's done — never hand over untested code. Add a quick smoke test for anything non-trivial.",
      "Install anything else with apt-get: `apt-get update && apt-get install -y <pkg>` (you are root).",
      "DISPLAY=:1 is preset, so GUI programs you launch appear on the desktop the user is watching.",
      "Long output is truncated; write large results to /READ_WRITE_FILES or summarize.",
    ].join("\n"),
  },
  {
    name: "internet",
    category: "internet",
    summary: "Read web pages/APIs (fetch_url) and search the web (web_search).",
    details: [
      "web_search(query) returns result titles + URLs. Pick relevant ones, then fetch_url(url) to read the content (HTML is stripped to text).",
      "fetch_url also calls JSON/HTTP APIs directly.",
      "You have OPEN internet access (no allow-list). Prefer official APIs when available.",
      "Typical research flow: web_search -> fetch_url the best 1-3 results -> synthesize -> (optionally) store findings with sql or write to /READ_WRITE_FILES.",
    ].join("\n"),
  },
  {
    name: "web-preview",
    category: "desktop",
    summary: "Let the user preview/test a web app in their own browser before you hand over the code.",
    details: [
      "GOAL: the user opens a URL and gets a WORKING, interactive page. The #1 mistake is building only API endpoints (POST /save, GET /data) with no UI — then GET / is 'Cannot GET /' and it looks broken. ALWAYS serve a real HTML page at GET / with the actual interface (forms, buttons, fetch() calls to your own endpoints).",
      "Steps: 1) build the app under /workspace; 2) serve_app(command, port) on a preview port 9101-9150 bound to 0.0.0.0; 3) check the result — ok_homepage must be true / status 200 at /. If not, FIX it (usually: add the homepage route/index.html) and call serve_app again. Only tell the user the URL once GET / returns 200.",
      "4) TEST the actual functionality before handing over: curl the API routes (e.g. POST to the form endpoint then GET it back and confirm the data round-trips), and/or use Playwright to load the page, submit input, and verify the response. Fix any failure and re-run. Then tell the user the URL and briefly what you tested.",
      "Bind to 0.0.0.0 (NOT 127.0.0.1/localhost) and use a preview port 9101-9150 (port 3000/8080 etc. are NOT exposed to the host).",
      "Prefer the SIMPLEST stack that shows a UI: a single static index.html (serve with `python3 -m http.server <port> --bind 0.0.0.0`), or one Express/Flask file that returns an HTML page at '/' and has any API routes it needs. Avoid heavy build steps (Vite/Next) for a quick demo unless asked.",
      "Iterate in place: keep ONE app dir, fix and re-run serve_app — do not scatter multiple half-built attempts.",
      "Minimal known-good Express demo (one file serves the UI at / AND an API):",
      "  const e=require('express'),app=e();app.use(e.json());let items=[];",
      "  app.get('/',(q,r)=>r.type('html').send(`<h1>Demo</h1><input id=i><button onclick=\"fetch('/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({v:i.value})}).then(()=>load())\">Add</button><ul id=l></ul><script>async function load(){l.innerHTML=(await (await fetch('/items')).json()).map(x=>'<li>'+x+'</li>').join('')}load()</script>`));",
      "  app.post('/add',(q,r)=>{items.push(q.body.v);r.json({ok:true})});app.get('/items',(q,r)=>r.json(items));",
      "  app.listen(9105,'0.0.0.0',()=>console.log('up'));",
      "Then: serve_app('node app.js', 9105). After the user is happy, save the final source to /READ_WRITE_FILES.",
    ].join("\n"),
  },
  {
    name: "browser-automation",
    category: "internet",
    summary: "Drive a real headless browser with Playwright (scrape, test, fill forms).",
    details: [
      "Playwright (Python) is preinstalled with Chromium + Firefox. PREFER it over pixel computer-use (screenshot/click) for scraping, form-filling, and web-app testing — it is far more reliable and token-efficient (works from the DOM/accessibility tree, not pixels).",
      "Run it via run_shell, e.g.:",
      "  python3 - <<'PY'",
      "  from playwright.sync_api import sync_playwright",
      "  with sync_playwright() as p:",
      "      b = p.chromium.launch()",
      "      pg = b.new_page(); pg.goto('https://example.com')",
      "      print(pg.title()); print(pg.inner_text('body')[:2000])",
      "      pg.screenshot(path='/READ_WRITE_FILES/page.png'); b.close()",
      "  PY",
      "Use `page.get_by_role/get_by_text` to locate elements, `.click()/.fill()` to act, `.content()` for HTML.",
      "Use the visual desktop computer-use tools (screenshot/click) only when you must operate the on-screen GUI the user is watching, or a non-browser app.",
    ].join("\n"),
  },
  {
    name: "desktop-control",
    category: "desktop",
    summary: "See and operate the GUI desktop (browser + apps) with screenshots.",
    details: [
      "This is computer use: you act by looking at the screen, like a person.",
      "ALWAYS screenshot first to see the current screen (the image is returned to you). The screen is 1024x768; coordinates are pixels from the top-left.",
      "Actions: open_url(url) / open_app(cmd), click(x,y), double_click, right_click, move_mouse, type_text(text), press_key(keys) [xdotool keysyms: Return, Tab, ctrl+l, ctrl+t, BackSpace], scroll(direction, amount).",
      "Loop: screenshot -> decide -> act -> screenshot to verify -> repeat. Never click blind; locate the element in the latest screenshot.",
      "To focus a browser address bar use press_key('ctrl+l'), then type_text, then press_key('Return').",
    ].join("\n"),
  },
  {
    name: "shared-files",
    category: "files",
    summary: "Exchange files with the user via the shared folders.",
    details: [
      "list_dir, read_file, write_file operate in the shared folders.",
      "/READ_ONLY_FILES is READ-ONLY to you (the user puts files there for you to read).",
      "/READ_WRITE_FILES is READ/WRITE — put any files you produce there so the user can pick them up.",
      "write_file OVERWRITES by default; pass append=true to add to the end (it also guarantees each entry starts on a new line).",
      "For recurring/periodic LOGS, use append_log(path, message) instead — the code stamps a uniform ISO timestamp and writes exactly one consistent line per entry, so a logging task never drifts in format or runs lines together across runs. Pass optional structured data via fields={k:v}. Do NOT add your own timestamp.",
      "For big outputs from run_shell, write to /READ_WRITE_FILES rather than dumping into chat.",
    ].join("\n"),
  },
  {
    name: "create-documents",
    category: "files",
    summary: "Create documents and images in any popular format in the workbench.",
    details: [
      "You are root with internet, so install whatever you need — never say you cannot.",
      "Preinstalled: pandoc, chromium, and Python libs fpdf2, reportlab, python-docx, python-pptx, openpyxl, pillow, matplotlib, markdown, plus imagemagick.",
      "PDF (programmatic): Python fpdf2 or reportlab (no external engine needed).",
      "PDF (formatted, from Markdown): pandoc `input.md -o tmp.html`, then `chromium --headless --no-sandbox --print-to-pdf=/READ_WRITE_FILES/out.pdf tmp.html`.",
      "Word DOCX: pandoc `-o out.docx`, or python-docx (programmatic control).",
      "PowerPoint PPTX: python-pptx. Excel XLSX: openpyxl. ODT/ODS/ODP, EPUB, RTF, HTML: pandoc.",
      "Images: Pillow (PIL) to create/edit, matplotlib for charts/plots, imagemagick `convert` for format conversion/resizing.",
      "CSV/JSON/TXT/MD: write directly with write_file.",
      "Always save the finished file into the read-write shared folder (/READ_WRITE_FILES) so the user gets it, then tell them the path.",
    ].join("\n"),
  },
  {
    name: "credentials",
    category: "credentials",
    summary: "Manage and use the user's OWN account logins (vault).",
    details: [
      "list_secrets -> names/usernames/urls (no passwords). get_secret(name) -> full credential incl. password, to log in.",
      "set_secret(name, {username,password,url,notes}) -> create or update (partial updates allowed). delete_secret(name) -> remove.",
      "Only operate accounts the user already OWNS. Do NOT create new accounts or bypass sign-up CAPTCHAs / phone verification.",
      "After the user gives you a login, save it with set_secret so you can reuse it.",
    ].join("\n"),
  },
  {
    name: "scheduling",
    category: "scheduling",
    summary: "Run tasks later/recurring and notify the user.",
    details: [
      "schedule_task(prompt, ...): one-shot with in_seconds (delay) or at (absolute ISO datetime); recurring with every_seconds plus an optional plain-language `until` stop condition.",
      "Compute times from the current date/time you are given each turn (e.g. 'in 10 minutes' -> in_seconds 600; 'at 5pm' -> today's ISO at 17:00).",
      "list_tasks to view; update_task(id, ...) to CHANGE an existing task in place (keeps it running — ALWAYS use this to modify a task, never cancel + reschedule); cancel_task(id) to stop one.",
      "notify_user(message) alerts the user (in-app, browser, desktop, spoken). For a recurring monitor, call notify_user only when the `until` condition is met — that also stops the task.",
    ].join("\n"),
  },
  {
    name: "workflow-login-and-act",
    category: "workflow",
    summary: "Log into a site the user owns and do something there.",
    details: [
      "1) get_secret(name) for the account (or ask the user / save with set_secret if new).",
      "2) open_url(login page) -> screenshot.",
      "3) Click the username field, type_text(username); click the password field, type_text(password).",
      "4) Click the sign-in button (locate it in the screenshot) or press_key('Return').",
      "5) screenshot to confirm you are logged in, then continue the task.",
      "If a CAPTCHA or phone verification appears, stop and ask the user to complete it — do not attempt to bypass it.",
    ].join("\n"),
  },
  {
    name: "workflow-monitor-and-alert",
    category: "workflow",
    summary: "Watch something on an interval and notify when a condition is met.",
    details: [
      "Use schedule_task with every_seconds (the interval) and until (the condition in plain language).",
      "Make the task prompt do the check (run_shell / fetch_url / sql / screenshot as appropriate).",
      "When the condition is met, call notify_user with the important details — this stops the recurring task.",
      "When it is not met, just report a one-line status and do not notify.",
      "The user can also say 'stop' and you cancel_task it.",
    ].join("\n"),
  },
];
